version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "laravel_db"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: ""
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db
      ports:
        - 8181:80
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: Secret
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: "laravelapp"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

